### ISSUE TITLE
Remove unwanted variables

### ISSUE THREAD

**Issue by vernwalrahul** [KgpKubs/robocup#19]

**Comment by shamin1998** [comment]
shamin aggarwal working on this

**Comment by shamin1998** [comment]
removed ball_in_our_possession

**Comment by shamin1998** [comment]
removed opp_bot_marking_our_attacker

**Comment by saurabhkgp21** [comment]
@shamin1998 Instead of commenting your updates, you can also create a PR from your fork repo referring this issue. Now whenever you'll commit to your fork it will update the PR accordingly.

**Comment by shamin1998** [comment]
Ok, done. I've described what changes I've made in the commit comments. If there's any changes to be made, please let me know.
