### ISSUE TITLE
Update GoToBall.py

### ISSUE THREAD

**Issue by vernwalrahul** [KgpKubs/robocup#23]
- Predict ball position

**Comment by thebhatman** [comment]
Me and Snehal are working on GoToBall.py for interception of moving ball.

**Comment by saurabhkgp21** [comment]
@thebhatman @Snehal-Reddy updates?

**Comment by thebhatman** [comment]
@sa

> @thebhatman @Snehal-Reddy updates?

We have made progress. We have added intercept state in GoToBall when the ball is moving. Right now it is going in to the state but the interception point is wrongly calculated. We are trying to fix it.
