### ISSUE TITLE
Create KickToPoint.py

### ISSUE THREAD

**Issue by vernwalrahul** [KgpKubs/robocup#25]

**Comment by thebhatman** [comment]
Me, Snehal, Prashant, Vishal will work on this.

**Comment by saurabhkgp21** [comment]
@VISHAL-RAJ-RAJ any update?

**Comment by ghost** [comment]
@saurabhkgp21 ... me and prashant were looking into #21, it's almost done, only some minor changes are left. I will look into #25 today.

**Comment by ghost** [comment]
I have sent a pull request ( #30  ).
