### ISSUE TITLE
Shift from memcache

### ISSUE THREAD

**Issue by saurabhkgp21** [KgpKubs/robocup#74]
Update following files
- /README.md
- /_Goalie_.py
- /bs.py
- /kgpkubs_launch/scripts/ssl.sh
- /role/_GoToPoint.py
- /tactics/CoPass.py
- /tactics/Goalie.py
- /tactics/_Goalie_.py
- /tactics/sample_tactic.py
- /tests/pid_tune.py

@ultrainstinct30

**Comment by saurabhkgp21** [comment]
Ref: #52

**Comment by ultrainstinct30** [comment]
I have updated all the files except bs.py and ssl.sh as I am not sure what changes do I make in them. I have committed those updates in my fork and once I update the rest of the files, I'll send a PR. What should I do about bs.py and ssl.sh?
